version: "3.8"
services:

  database:
    container_name: database
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "./database-data:/var/lib/postgresql/data"  
    networks:
      - backend

  cache:
    container_name: redis
    image: redis:alpine
    volumes:
      - "./healthchecks:/healthchecks"
    networks:
      - backend

  worker:
    container_name: worker
    build:
      context: ./worker
      dockerfile: Dockerfile
    image: worker-app
    depends_on:
      - database
      - cache
    networks:
      - backend
  
  voting:
    container_name: voting
    build:
      context: ./vote
      dockerfile: Dockerfile
    image: voting-app
    depends_on:
      - database
      - cache
      - worker
    networks:
      - frontend
      - backend
    ports:
      - "8081:80"
 
  result:
    container_name: result
    build:
      context: ./result
      dockerfile: Dockerfile
    image: result-app
    depends_on:
      - database
      - cache
      - worker
    networks:
      - backend
      - frontend
    ports:
      - "8080:80"

volumes:
  database-data:
  healthchecks:

networks:
  frontend:
  backend: